---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-greeter-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fast-greeter
  template:
    metadata:
      labels:
        app: fast-greeter
    spec:
      containers:
      - name: fast-greeter-container
        image: parijatkasbekar/fast-greeter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        



---
apiVersion: v1
kind: Service
metadata:
  name: fast-greeter-service
spec:
  selector:
    app: fast-greeter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
